<?php
/**
 * @var \LegalWeb\Cloud\Block\Config $block
 * @TODO - Output JS & CSS with \Magento\Framework\View\Helper\SecureHtmlRenderer::renderTag
 */
$generalConfig = $block->getSerializedGeneralConfig();
$integrationConfig = $block->getSerializedIntegrationConfig();
$js            = $block->getPopupJs();
$css           = $block->getPopupCss();
?>
<script>
    var spDsgvoGeneralConfig = <?= $generalConfig ?>;
    var spDsgvoIntegrationConfig = <?= $integrationConfig ?>;
</script>
<?php if ($js): ?>
<script><?= $js ?></script>
<?php endif; ?>

<?php if ($css): ?>
<style><?= $css ?></style>
<?php endif; ?>
